### ISSUE TITLE
Django 1.4 - braces tag 1.4.0 error

### ISSUE THREAD

**Issue by alexsilva** [brack3t/django-braces#182]
The doc on github says that works but is not working.

1.4.x will be the last version to officially support Django 1.4.x

Django 1.4.1-final, 0

```
ImportError at /admin/xxxxx
cannot import name force_text
```

**Comment by alexsilva** [comment]
Same error with braces tag 1.3.1

**Comment by chrisjones-brack3t** [comment]
It would help if you shared the code that was causing the error.

**Comment by alexsilva** [comment]
There is in my version of django

from django.utils.encoding import force_text

This should be the only version that works because it has no 'force_text'

https://github.com/brack3t/django-braces/blob/v1.2.0/braces/views.py

Error cause:
https://github.com/brack3t/django-braces/blob/v1.4.0/braces/views/_access.py#L8

**Comment by alexsilva** [comment]
I just test here and the only version that worked with django Django 1.4.1-final was tagged 1.2.0

**Comment by chrisjones-brack3t** [comment]
The latest version of the 1.4.x LTS release is [Django v.1.4.20](https://docs.djangoproject.com/en/1.4/releases/1.4.20/). You should be running the latest release of the 1.4.x branch. If you run the latest release, you will not have this import error.

**Comment by chrisjones-brack3t** [comment]
I'm going to close this as it's a non-issue if you're running the latest version (which you should so that you get all the security updates). It looks like force_text was added in [Django v1.4.2](https://github.com/django/django/blob/1.4.2/django/utils/encoding.py).

**Comment by alexsilva** [comment]
You could tell on github reference braces only supports django 1.4.x > 1.4.1, using tag 1.4.0

```
django-braces 1.4.x will be the last version to officially support Django 1.4.x
```

**Comment by alexsilva** [comment]
I do not have the option of upgrading the django, because it is an old and big project too much for that.

**Comment by chrisjones-brack3t** [comment]
If you look at our test suite, specifically [tox.ini](https://github.com/brack3t/django-braces/blob/master/tox.ini), you'll notice we test Django versions like this: `Django>=1.5,<1.6`. That means we test against whatever version of 1.5.x is the newest (just using 1.5.x as an example). As of writing this, that is v1.5.12. We don't test against every iteration in the 1.5.x branch. The `.x` releases are bug/security fixes that you should **absolutely** be upgrading to when they come out.

You can step through the release notes for each version of [1.4.x here](https://docs.djangoproject.com/en/1.4/releases/1.4.20/). The release notes will let you know if there are any backwards incompatible changes you need to be aware of. Django is also very good at throwing errors/warnings if you are using something that is deprecated or pending deprecation.

Your project may be old, but upgrading from v1.4.1 to v1.4.20 should not cause any problems. Jumping major point releases e.g. 1.4.x to 1.5.x is usually where you have to be careful of things breaking.

I will add a ticket to update the README to state more clearly that we support the most recent bug/security release of each version and not every single release.
